[project]
name = "fuck-izanmei"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "flask[async]>=3.1.1",
    "httpx>=0.28.1",
]
